#!/usr/bin/env php
<?php

// Load the composer autoloader
require __DIR__ . '/vendor/autoload.php';

/** @var \Spark\Foundation\Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

$app->withContainer(function (\Spark\Container $container) {
    $container->addServiceProvider(new \Spark\Foundation\Providers\CommandsServiceProvider);
    $container->addServiceProvider(new \App\Providers\ConsoleServiceProvider);
});

$app->withCommands(function () {
    require __DIR__ . '/routes/console.php';
});

$app->handleCommand(); // Run the application

exit;
